'use client'
import InputField from '@/app/components/InputField'
import SelectField from '@/app/components/SelectField'
import { useState } from 'react'

export default function VisitDetails() {
  const [formData, setFormData] = useState({
    visitId: 'Auto',
    doctor: '',
    dateOfExamination: '',
    timeOfExamination: '',
    department: '',
    generatedBy: ''
  })

  const handleChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  const handleSubmit = () => {
    localStorage.setItem('visitDetails', JSON.stringify(formData))
    alert('Visit details saved! Proceed to Vitals.')
  }

  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <h2 className="text-lg font-semibold text-gray-800 mt-[-12px] mb-1">Visit Details</h2>
      <hr className="border-t border-gray-300 mb-4 mx-3 md:mx-4" />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <InputField
          label="Visit ID"
          value={formData.visitId}
          disabled
          placeholder="Auto-generated"
        />
        <SelectField
          label="Doctor"
          options={['Dr. Smith', 'Dr. Patel', 'Dr. Rao']}
          value={formData.doctor}
          onChange={e => handleChange('doctor', e.target.value)}
        />
        <InputField
          label="Date of Examination"
          type="date"
          value={formData.dateOfExamination}
          onChange={e => handleChange('dateOfExamination', e.target.value)}
        />
        <InputField
          label="Time of Examination"
          type="time"
          value={formData.timeOfExamination}
          onChange={e => handleChange('timeOfExamination', e.target.value)}
          placeholder="Select time"
        />
        <InputField
          label="Department"
          value={formData.department}
          onChange={e => handleChange('department', e.target.value)}
          placeholder="e.g., Auto fetch from doctor mapping"
        />
        <InputField
          label="Generated by"
          value={formData.generatedBy}
          onChange={e => handleChange('generatedBy', e.target.value)}
          placeholder="e.g., Auto"
        />
      </div>

      <div className="mt-6">
        <button
          className="bg-blue-600 text-white px-5 py-2 rounded hover:bg-blue-700"
          onClick={handleSubmit}
        >
          Send for Vitals
        </button>
      </div>
    </div>
  )
}
